import type { Metadata } from 'next'
import './globals.css'
import { Inter as FontSans } from 'next/font/google';
import { cn } from '@/lib/utils';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const fontSans = FontSans({
  subsets: ['latin'], 
  weight: ['400', '700'],
  variable: '--font-sans', 
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialised",
          fontSans.variable
        )}
      >
        {children}
      </body>
    </html>
  )
}
